version: '2'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
#      - '80:80'
#      - '443:443'
#      - '22:22'
    volumes:
      - '/var/lib/ilus/gitlab/config:/etc/gitlab'
      - '/var/lib/ilus/gitlab/logs:/var/log/gitlab'
      - '/var/lib/ilus/gitlab/data:/var/opt/gitlab'
