version: '2'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    hostname: 'gitlab.ilus.pw'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.ilus.pw'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '29175:80'
      - '29176:443'
      - '29177:22'
    volumes:
      - '/var/lib/ilus/gitlab/config:/etc/gitlab'
      - '/var/lib/ilus/gitlab/logs:/var/log/gitlab'
      - '/var/lib/ilus/gitlab/data:/var/opt/gitlab'
    restart: unless-stopped
