version: '2'

services:
  diskover:
    image: linuxserver/diskover
    container_name: diskover
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Paris
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=changeme
      - INDEX_NAME=diskover-
      - DISKOVER_OPTS=
      - WORKER_OPTS=
      - RUN_ON_START=true
      - USE_CRON=true
    volumes:
      - /var/lib/ilus/diskover/config:/config
      - /var/lib/ilus/diskover/data:/data
    ports:
      - 29185:80
      - 9181:9181
      - 9999:9999
    networks:
      - diskover
    mem_limit: 4096m
    depends_on:
      - elasticsearch
      - redis

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - /var/lib/ilus/diskover/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    networks:
      - diskover
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - /var/lib/ilus/diskover/redis:/data
    networks:
      - diskover

networks:
  diskover:
