version: "2.1"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Paris
      - MEM_LIMIT=1024M #optional
    volumes:
      - /var/lib/ilus/unifi-controller:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
#      - 1900:1900/udp #optional - Jellyfin always tries to bind this for DLNA even though it's disabled, and it's not important for the unifi controller.
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514 #optional
