version: "2"

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - /var/lib/ilus/monitoring/grafana:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - /var/lib/ilus/monitoring/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_ENABLED=true

  telegraf:
    image: antoine42/telegraf
    container_name: telegraf
    privileged: true
    networks:
      - monitoring
    volumes:
      - /var/lib/ilus/monitoring/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /storage/temp/watch:/storage
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  monitoring:
