version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Paris
    volumes:
      - /var/lib/ilus/jackett:/config
      - /storage/temp/watch:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
