version: "2"

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Paris
      - URL=antoine-dujardin.com
      - EXTRA_DOMAINS=*.antoine-dujardin.com #,rocket-comparator.com,*.rocket-comparator.com
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=antoinedujardin42@gmail.com
      - DHLEVEL=2048 #optional
      - STAGING=false #optional
    volumes:
      - /var/lib/ilus/nginx:/config
      - /var/log/auth.log:/config/log/auth.log # fail2ban SSH
      - /home/antoine/git/rocket_comparator:/rocket_comparator
    ports:
      - 192.168.0.15:443:443
      - 192.168.0.15:80:80
    restart: unless-stopped
