version: '3'

services:
  pritunl:
    image: jippi/pritunl
    container_name: pritunl
    privileged: true
    volumes:
      - /var/lib/ilus/pritunl/mongodb:/var/lib/mongodb
      - /var/lib/ilus/pritunl/pritunl:/var/lib/pritunl
      - /var/lib/ilus/pritunl/pritunl.conf:/etc/pritunl.conf
    ports:
      - 29185:80
      - 29186:443
      - 1194:1194
      - 1194:1194/udp
      - 1195:1195/udp
      - 12109:12109
