version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Paris
      - SERVERURL=wireguard.antoine-dujardin.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=10 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /var/lib/ilus/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    networks:
      - wireguard
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  wireguard:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1420
