version: "2"

services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Paris
    volumes:
      - /var/lib/ilus/sonarr:/config
      - /mnt/storage/media/series:/tv
      - /mnt/storage/temp/sonarr:/downloads/sonarr
      - /mnt/storage/temp/series:/downloads/series
    ports:
      - 8989:8989
    restart: unless-stopped
