version: '3'
services:
  plex:
    container_name: tautulli
    image: tautulli/tautulli
    ports:
      - 8181:8181
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=998
    network_mode: host
    volumes:
      - /var/lib/ilus/tautulli:/config
      - /var/lib/ilus/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro
