version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 192.168.0.20:53:53/tcp
      - 192.168.0.20:53:53/udp
      - 192.168.0.20:67:67/udp
      - 192.168.0.20:80:80/tcp
      - 192.168.0.20:443:443/tcp
    environment:
      - TZ=Europe/Paris
    volumes:
      - '/var/lib/ilus/pi-hole/conf:/etc/pihole/'
      - '/var/lib/ilus/pi-hole/dnsmasq:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
