version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 192.168.0.20:53:53
      - 192.168.0.20:67:67
      - 192.168.0.20:80:80
      - 192.168.0.20:443:443
    environment:
      - TZ=Europe/Paris
    volumes:
      - '/var/lib/ilus/pi-hole/conf:/etc/pihole/'
      - '/var/lib/ilus/pi-hole/dnsmasq:/etc/dnsmasq.d/'
    dns:
      - 1.1.1.1
      - 9.9.9.9
    cap_add:
      - NET_ADMIN
