version: "2"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Paris
    volumes:
      - /var/lib/ilus/radarr:/config
      - /storage/media/movies:/movies
      - /storage/temp/radarr:/downloads/radarr
      - /storage/temp/movies:/downloads/movies
    ports:
      - 7878:7878