version: "2"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Paris
    volumes:
      - /var/lib/ilus/lidarr:/config
      - /storage/media/music:/music
      - /storage/temp/lidarr:/downloads/lidarr
    ports:
      - 8686:8686
