version: "2"
services:
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Paris
    volumes:
      - /var/lib/ilus/lazylibrarian:/config
      - /mnt/storage/media/books/ebooks:/books
      - /mnt/storage/media/books/audiobooks:/audiobooks
      - /mnt/storage/temp/lazylibrarian:/downloads/lazylibrarian
    ports:
      - 5299:5299
    restart: unless-stopped
