version: '3'

services:
  db:
    image: postgres
    volumes:
      - /var/lib/ilus/nextcloud/db:/var/lib/postgresql/data
    env_file:
      - db.env
    restart: unless-stopped

  app:image: nextcloud:apache
    ports:
      - 8081:80
    volumes:
      - /var/lib/ilus/nextcloud/app:/var/www/html
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    restart: unless-stopped
