version: "2.1"

services:
  nextcloud_db:
    image: postgres
    volumes:
      - /var/lib/ilus/nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    networks:
      - nextcloud
    restart: unless-stopped

  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Paris
    volumes:
      - /var/lib/ilus/nextcloud/config:/config
      - /var/lib/ilus/nextcloud/data:/data
    ports:
      - 29201:443
    networks:
      - nextcloud
    restart: unless-stopped

networks:
  nextcloud:
